// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v5.28.2
// source: claims.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StandardClaims struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Issuer    string   `protobuf:"bytes,1,opt,name=Issuer,proto3" json:"Issuer,omitempty"`
	Subject   string   `protobuf:"bytes,2,opt,name=Subject,proto3" json:"Subject,omitempty"`
	Audience  []string `protobuf:"bytes,3,rep,name=Audience,proto3" json:"Audience,omitempty"`
	ExpiresAt int64    `protobuf:"varint,4,opt,name=ExpiresAt,proto3" json:"ExpiresAt,omitempty"`
	NotBefore int64    `protobuf:"varint,5,opt,name=NotBefore,proto3" json:"NotBefore,omitempty"`
	IssuedAt  int64    `protobuf:"varint,6,opt,name=IssuedAt,proto3" json:"IssuedAt,omitempty"`
	ID        string   `protobuf:"bytes,7,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *StandardClaims) Reset() {
	*x = StandardClaims{}
	mi := &file_claims_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StandardClaims) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StandardClaims) ProtoMessage() {}

func (x *StandardClaims) ProtoReflect() protoreflect.Message {
	mi := &file_claims_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StandardClaims.ProtoReflect.Descriptor instead.
func (*StandardClaims) Descriptor() ([]byte, []int) {
	return file_claims_proto_rawDescGZIP(), []int{0}
}

func (x *StandardClaims) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}

func (x *StandardClaims) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *StandardClaims) GetAudience() []string {
	if x != nil {
		return x.Audience
	}
	return nil
}

func (x *StandardClaims) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *StandardClaims) GetNotBefore() int64 {
	if x != nil {
		return x.NotBefore
	}
	return 0
}

func (x *StandardClaims) GetIssuedAt() int64 {
	if x != nil {
		return x.IssuedAt
	}
	return 0
}

func (x *StandardClaims) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

var File_claims_proto protoreflect.FileDescriptor

var file_claims_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x63, 0x6c, 0x61, 0x69, 0x6d, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03,
	0x70, 0x77, 0x74, 0x22, 0xc6, 0x01, 0x0a, 0x0e, 0x53, 0x74, 0x61, 0x6e, 0x64, 0x61, 0x72, 0x64,
	0x43, 0x6c, 0x61, 0x69, 0x6d, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x49, 0x73, 0x73, 0x75, 0x65, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x49, 0x73, 0x73, 0x75, 0x65, 0x72, 0x12, 0x18,
	0x0a, 0x07, 0x53, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x53, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x41, 0x75, 0x64, 0x69,
	0x65, 0x6e, 0x63, 0x65, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x41, 0x75, 0x64, 0x69,
	0x65, 0x6e, 0x63, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x45, 0x78, 0x70, 0x69, 0x72, 0x65, 0x73, 0x41,
	0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x45, 0x78, 0x70, 0x69, 0x72, 0x65, 0x73,
	0x41, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x4e, 0x6f, 0x74, 0x42, 0x65, 0x66, 0x6f, 0x72, 0x65, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x4e, 0x6f, 0x74, 0x42, 0x65, 0x66, 0x6f, 0x72, 0x65,
	0x12, 0x1a, 0x0a, 0x08, 0x49, 0x73, 0x73, 0x75, 0x65, 0x64, 0x41, 0x74, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x08, 0x49, 0x73, 0x73, 0x75, 0x65, 0x64, 0x41, 0x74, 0x12, 0x0e, 0x0a, 0x02,
	0x49, 0x44, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x42, 0x1a, 0x5a, 0x18,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6c, 0x6b, 0x79, 0x7a, 0x68,
	0x75, 0x2f, 0x70, 0x77, 0x74, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_claims_proto_rawDescOnce sync.Once
	file_claims_proto_rawDescData = file_claims_proto_rawDesc
)

func file_claims_proto_rawDescGZIP() []byte {
	file_claims_proto_rawDescOnce.Do(func() {
		file_claims_proto_rawDescData = protoimpl.X.CompressGZIP(file_claims_proto_rawDescData)
	})
	return file_claims_proto_rawDescData
}

var file_claims_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_claims_proto_goTypes = []any{
	(*StandardClaims)(nil), // 0: pwt.StandardClaims
}
var file_claims_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_claims_proto_init() }
func file_claims_proto_init() {
	if File_claims_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_claims_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_claims_proto_goTypes,
		DependencyIndexes: file_claims_proto_depIdxs,
		MessageInfos:      file_claims_proto_msgTypes,
	}.Build()
	File_claims_proto = out.File
	file_claims_proto_rawDesc = nil
	file_claims_proto_goTypes = nil
	file_claims_proto_depIdxs = nil
}
