// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v5.28.2
// source: custom.proto

package custom

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StandardClaims struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Issuer    string   `protobuf:"bytes,1,opt,name=Issuer,proto3" json:"Issuer,omitempty"`
	Subject   string   `protobuf:"bytes,2,opt,name=Subject,proto3" json:"Subject,omitempty"`
	Audience  []string `protobuf:"bytes,3,rep,name=Audience,proto3" json:"Audience,omitempty"`
	ExpiresAt int64    `protobuf:"varint,4,opt,name=ExpiresAt,proto3" json:"ExpiresAt,omitempty"`
	NotBefore int64    `protobuf:"varint,5,opt,name=NotBefore,proto3" json:"NotBefore,omitempty"`
	IssuedAt  int64    `protobuf:"varint,6,opt,name=IssuedAt,proto3" json:"IssuedAt,omitempty"`
	ID        string   `protobuf:"bytes,7,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *StandardClaims) Reset() {
	*x = StandardClaims{}
	mi := &file_custom_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StandardClaims) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StandardClaims) ProtoMessage() {}

func (x *StandardClaims) ProtoReflect() protoreflect.Message {
	mi := &file_custom_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StandardClaims.ProtoReflect.Descriptor instead.
func (*StandardClaims) Descriptor() ([]byte, []int) {
	return file_custom_proto_rawDescGZIP(), []int{0}
}

func (x *StandardClaims) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}

func (x *StandardClaims) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *StandardClaims) GetAudience() []string {
	if x != nil {
		return x.Audience
	}
	return nil
}

func (x *StandardClaims) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *StandardClaims) GetNotBefore() int64 {
	if x != nil {
		return x.NotBefore
	}
	return 0
}

func (x *StandardClaims) GetIssuedAt() int64 {
	if x != nil {
		return x.IssuedAt
	}
	return 0
}

func (x *StandardClaims) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

type CustomClaims struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Claims *StandardClaims `protobuf:"bytes,1,opt,name=claims,proto3" json:"claims,omitempty"`
	Name   string          `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Age    int64           `protobuf:"varint,3,opt,name=Age,proto3" json:"Age,omitempty"`
}

func (x *CustomClaims) Reset() {
	*x = CustomClaims{}
	mi := &file_custom_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomClaims) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomClaims) ProtoMessage() {}

func (x *CustomClaims) ProtoReflect() protoreflect.Message {
	mi := &file_custom_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomClaims.ProtoReflect.Descriptor instead.
func (*CustomClaims) Descriptor() ([]byte, []int) {
	return file_custom_proto_rawDescGZIP(), []int{1}
}

func (x *CustomClaims) GetClaims() *StandardClaims {
	if x != nil {
		return x.Claims
	}
	return nil
}

func (x *CustomClaims) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CustomClaims) GetAge() int64 {
	if x != nil {
		return x.Age
	}
	return 0
}

var File_custom_proto protoreflect.FileDescriptor

var file_custom_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x22, 0xc6, 0x01, 0x0a, 0x0e, 0x53, 0x74, 0x61, 0x6e, 0x64,
	0x61, 0x72, 0x64, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x49, 0x73, 0x73,
	0x75, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x49, 0x73, 0x73, 0x75, 0x65,
	0x72, 0x12, 0x18, 0x0a, 0x07, 0x53, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x53, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x41,
	0x75, 0x64, 0x69, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x41,
	0x75, 0x64, 0x69, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x45, 0x78, 0x70, 0x69, 0x72,
	0x65, 0x73, 0x41, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x45, 0x78, 0x70, 0x69,
	0x72, 0x65, 0x73, 0x41, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x4e, 0x6f, 0x74, 0x42, 0x65, 0x66, 0x6f,
	0x72, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x4e, 0x6f, 0x74, 0x42, 0x65, 0x66,
	0x6f, 0x72, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x49, 0x73, 0x73, 0x75, 0x65, 0x64, 0x41, 0x74, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x49, 0x73, 0x73, 0x75, 0x65, 0x64, 0x41, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x22,
	0x64, 0x0a, 0x0c, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x73, 0x12,
	0x2e, 0x0a, 0x06, 0x63, 0x6c, 0x61, 0x69, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x16, 0x2e, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x2e, 0x53, 0x74, 0x61, 0x6e, 0x64, 0x61, 0x72,
	0x64, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x73, 0x52, 0x06, 0x63, 0x6c, 0x61, 0x69, 0x6d, 0x73, 0x12,
	0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x41, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x03, 0x41, 0x67, 0x65, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x63, 0x75, 0x73, 0x74, 0x6f,
	0x6d, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_custom_proto_rawDescOnce sync.Once
	file_custom_proto_rawDescData = file_custom_proto_rawDesc
)

func file_custom_proto_rawDescGZIP() []byte {
	file_custom_proto_rawDescOnce.Do(func() {
		file_custom_proto_rawDescData = protoimpl.X.CompressGZIP(file_custom_proto_rawDescData)
	})
	return file_custom_proto_rawDescData
}

var file_custom_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_custom_proto_goTypes = []any{
	(*StandardClaims)(nil), // 0: custom.StandardClaims
	(*CustomClaims)(nil),   // 1: custom.CustomClaims
}
var file_custom_proto_depIdxs = []int32{
	0, // 0: custom.CustomClaims.claims:type_name -> custom.StandardClaims
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_custom_proto_init() }
func file_custom_proto_init() {
	if File_custom_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_custom_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_custom_proto_goTypes,
		DependencyIndexes: file_custom_proto_depIdxs,
		MessageInfos:      file_custom_proto_msgTypes,
	}.Build()
	File_custom_proto = out.File
	file_custom_proto_rawDesc = nil
	file_custom_proto_goTypes = nil
	file_custom_proto_depIdxs = nil
}
